---
output: word_document
---
# Literature Cited

Canty A, Ripley BD (2020). boot: Bootstrap R (S-Plus) Functions. R package version 1.3-25.

Davison AC, Hinkley DV (1997). Bootstrap Methods and Their Applications. Cambridge University Press, Cambridge. ISBN 0-521-57391-2, http://statwww.epfl.ch/davison/BMA/.

De Caceres, M., Legendre, P. (2009). Associations between species and groups of sites: indices and statistical inference. Ecology, URL
http://sites.google.com/site/miqueldecaceres/ 

Douglas Bates, Martin Maechler, Ben Bolker, Steve Walker (2015). Fitting Linear Mixed-Effects Models Using lme4. Journal of Statistical Software, 67(1),
1-48. doi:10.18637/jss.v067.i01.

Dufrêne, M. & Legendre, P. (1997) Species assemblages and indicator species: the need for a flexible asymmetrical approach. Ecological Monographs, 67, 345–366.
Rassweiler et al 2018 - conversions to kelp biomass

McGeoch, M.A. & Chown, S.L. (1998) Scaling up the value of bioindicators. Trends in Ecology & Evolution, 13, 46–47.

Jari Oksanen, F. Guillaume Blanchet, Michael Friendly, Roeland Kindt, Pierre Legendre, Dan McGlinn, Peter R. Minchin, R. B. O'Hara, Gavin L. Simpson, Peter
Solymos, M. Henry H. Stevens, Eduard Szoecs and Helene Wagner (2019). vegan: Community Ecology Package. R package version 2.5-6.
https://CRAN.R-project.org/package=vegan

NEED TO CITE

+ ONI data
+ PDO data ? if we use it
+ PISCO fish data 2005-2006 ? if we use it
+ Biomass equations (Reed benthic, Kramp? fish or all individual fish equations?)